language: node_js
os:
- linux
node_js:
- stable
cache:
  directories:
  - node_modules
before_install:
- openssl aes-256-cbc -K $encrypted_ad31baa5a724_key -iv $encrypted_ad31baa5a724_iv
  -in fcm-key.json.enc -out fcm-key.json -d
- cd server/dbInterface
install:
- npm install
- cd ../requestManager
- npm install
- cd ../chatServer
- npm install
- cd ../tests
- npm ci
script:
- npm test
