language: node_js 

os:
  - linux

node_js:
  - "stable"

cache:
  directories:
  - node_modules


before_install:
  - openssl aes-256-cbc -K $encrypted_0a6446eb3ae3_key -iv $encrypted_0a6446eb3ae3_iv -in fcm-key.json.enc -out server/chatServer/fcm-key.json -d
  - cd dbInterface
  

install:
  - npm install
  - cd ../requestManager
  - npm install
  - cd ../chatServer
  - npm install
  - cd ../tests
  - npm ci

script:
  - npm test
